### ISSUE TITLE
Banks location in Streaming assets folder

### ISSUE THREAD

**Issue by jakubvlk** [fmod/UnityIntegration#24]
Hi,
I've just updated fmod studio and fmod integration package to latest version (2.00.01). It solved my problem with error about copying banks to Streaming assets folder. However I am experiencing another issue.

![image](https://user-images.githubusercontent.com/1968306/57770012-9fc1be00-770f-11e9-9a78-bbd065ccc579.png)

How you can see on the image, from some reason MasterBank and MasterBank.strings are outside of StreamingAssets/Assets/Fmod/Build/Desktop. These folder are created by fmod itself and when I delete them they will appear again. It's not big issues, but I like my project clean :-).

Any idea if I am missing some settings or it is a bug?

Thanks for your help,

Jakub.

**Comment by fmod-cameron** [comment]
The banks should be in the StreamingAssets folder root, unless you have specified a sub directory for them in Studio. 

If the folders are being recreated by the integration, I would recommend deleting the FMODStudioCache.asset file, the integration will create a new one and any old paths will be cleared.

**Comment by jakubvlk** [comment]
Deleting the FMODStudioCache.asset helped. Thank you!
