### ISSUE TITLE
FMODStudioCache causing deserialisation exceptions when Resource.LoadAll() is used in a build.

### ISSUE THREAD

**Issue by peperbol** [fmod/UnityIntegration#27]
Because the FMODStudioCache uses editor-only classes, it might cause errors if it is still present in a build, when unity tries to load and deserialize it.
This could happen when a script uses Resources.LoadAll("").

A solution to this problem would be to move the FMOD studiocache into an Editor folder.
So when looking at FMODUnity.EventManager in EventManager.cs changing the path on line 17 to:
`const string CacheAssetFullName = "Assets/Plugins/FMOD/Editor/Resources/" + CacheAssetName + ".asset";` 
would fix the issue.
This will result in the asset not being included in a build.

**Comment by fmod-cameron** [comment]
Thank you very much for the input, I have raised a task to fix this in an upcoming release.
