### ISSUE TITLE
Git URL for package only - Request

### ISSUE THREAD

**Issue by Vixxd** [fmod/UnityIntegration#28]
Is it possible for you to provide a Git URL for the FMOD integration that Unity will recognise as a custom unity package (i.e. https://docs.unity3d.com/Manual/CustomPackages.html)?

It would be really handy to add a project dependency for the FMOD integration directly into a Unity project's manifest.json (as outlined in the Unity manual here: https://docs.unity3d.com/Manual/upm-git.html), as it would be essentially be manageable through the package manager and automatically updated.

Reimporting manually is fine - just trying to see where I can improve my workflow.

**Comment by fmod-cameron** [comment]
We do have plans to make use of the Unity Package Manager in a future release.
