### ISSUE TITLE
CopyToStreamingAssets() called twice in a row?

### ISSUE THREAD

**Issue by RagtagShawn** [fmod/UnityIntegration#35]
In version v1.10.20 Unity integration package CopyToStreamingAssets() is called twice in a row when invoked via EventManager.Update. Once in OnCacheCange at the end of the method and again right after that in Update.

Also in EventManager.CopyToStreamingAssets in the last iteration loop you call AssetDatabase.SaveAssets every loop. Is that necessary? Can you not call it at the end of the loop?

This along with how often this method is invoked via Update is slowing down iteration time when working in the editor. It is invoked entering play mode or recompiling scripts when none of the FMOD bank assets have changed.

**Comment by fmod-cameron** [comment]
We have changes for these in 2.0 that can be used as a guide for manually modifying other versions.
https://github.com/fmod/UnityIntegration/blob/master/Assets/Plugins/FMOD/src/Editor/EventManager.cs
