### ISSUE TITLE
Significant editor performance hit (BankRefresher)

### ISSUE THREAD

**Issue by kamyker** [fmod/UnityIntegration#41]
Open profiler and select edit mode, deep profile:
![image](https://user-images.githubusercontent.com/9093037/218549437-b8cc7701-4179-4ee1-bbb5-e7c4e1eb8ea8.png)

**Comment by leahfmod** [comment]
Thanks for pointing this out - if possible, please head over to our forums at [https://qa.fmod.com/](https://qa.fmod.com/) and create a post about the issue with some more details so we can address it.

**Comment by kamyker** [comment]
> Thanks for pointing this out - if possible, please head over to our forums at https://qa.fmod.com/ and create a post about the issue with some more details so we can address it.

Website doesn't work for me, I get "Access denied Error code 1020". Tried many things including different browsers, disabling ad block etc.

**Comment by fmod-andrew** [comment]
> Website doesn't work for me, I get "Access denied Error code 1020". Tried many things including different browsers, disabling ad block etc.

That doesn't sound good. Send us an email at support@fmod.com with your fmod.com account details and we'll sort it out.

**Comment by kamyker** [comment]
> > Website doesn't work for me, I get "Access denied Error code 1020". Tried many things including different browsers, disabling ad block etc.
> 
> That doesn't sound good. Send us an email at [support@fmod.com](mailto:support@fmod.com) with your fmod.com account details and we'll sort it out.

Website finally started working. Thanks if you did anything to help, I was trying for 2+ months and only VPN worked.

**Comment by fmod-andrew** [comment]
> Website finally started working. Thanks if you did anything to help, I was trying for 2+ months and only VPN worked.

We did change a few things. Glad it's working for you now.
