### ISSUE TITLE
AttachInstanceToGameObject removes stopped instances

### ISSUE THREAD

**Issue by CharlieHess** [fmod/UnityIntegration#42]
I'm probably misunderstanding something, but [`AttachInstanceToGameObject`](https://github.com/fmod/fmod-for-unity/blob/2.02/Assets/Plugins/FMOD/src/RuntimeManager.cs#L462-L470) automatically removes instances that are in a stopped playback state.

My use case: I have a footstep event instance on my character class. I want to allocate the event instance and `Attach` it exactly once, in `Start`. I then want to play the footstep sound based on an animator callback, and have the 3D attributes automatically relayed. That seems to be the use case `Attach` was designed for, no? But it's essentially a noop: the instances are removed immediately after I call attach, because they haven't been played yet.

The only way to get this to work is to call `set3DAttributes` every `Update`, or just before the event is started. Which is fine and it works, but has me wondering: what is the purpose of `AttachInstanceToGameObject`?

``` cs
public class CharacterBase : MonoBehaviour {
  protected EventInstance _stepEvent;

  protected void Start() {
    _stepEvent = RuntimeManager.CreateInstance(_asset.StepSoundEvent);
    RuntimeManager.AttachInstanceToGameObject(_stepEvent, transform, _rigidBody); // has no effect, the attached instance is discarded immediately
  }

  protected void PlayStepSound() {
    _stepEvent.start();
  }
}
```

### What is his purpose?
![image](https://github.com/fmod/fmod-for-unity/assets/1865957/ac67f473-3c25-403f-bdb1-26598a602692)

**Comment by fmod-cameron** [comment]
We want to have a list of all the 3D Events that require their location update, but for performance reasons we don't want to do this for Events that are stopped.

That does seem less than ideal in this case, the intention is that you would call `AttachInstanceToGameObject` when you are calling `start()`. In this case you could call it in `PlayStepSound()`.

I can understand where you are coming from though and I'll raise a task to see if there is a better way we can go about this, even if its as simple as having an 'AutoRemove' parameter or something similar.
