### ISSUE TITLE
How do I change advanced settings from script?

### ISSUE THREAD

**Issue by CharlieHess** [fmod/UnityIntegration#43]
The API leads me to believe I can change things like the [idle sample data pool size](https://fmod.com/docs/2.01/api/studio-api-system.html#fmod_studio_advancedsettings). But in practice if I try to change these I get:

```
[FMOD] Manager::setAdvancedSettings : Cannot set advanced settings after Studio initialization
```

Looking over the source code, it appears the architecture is singleton-driven, so _fetching the RuntimeManager_ calls initialize. And I have to fetch the `RuntimeManager` to change the advanced settings. Is this impossible?

**Comment by Connor-FMOD** [comment]
Hi, 

In the RuntimeManager.cs script on line 326 there is an if statement which will apply FMOD Studio Advanced settings if an encryption key is present. I would suggest creating you own advanced settings and applying them outside this if statement. 

Hope this helps!

**Comment by CharlieHess** [comment]
Right, I know I can modify y'all's source code to do whatever I want, this was more of an API question. 😬 There is a public method `setAdvancedSettings` that currently serves no purpose, as it can only be called after initialization. Keeping it in the API in its current state is throwing sand in people's eyes. Perhaps:

1. Adding a pre-initialization callback that users can hook to call `setAdvancedSettings` safely _or_
2. Making the method private or adding documentation noting it serves no purpose, and recommending to modify the source code directly instead

**Comment by Connor-FMOD** [comment]
Hi, 

Apologies for the miss understanding. 

We already have pre-initialize call back here: https://fmod.com/docs/2.02/unity/examples-callback-handler.html. 

Hope this helps.
