### ISSUE TITLE
Total or Virtual?

### ISSUE THREAD

**Issue by YunusYld** [fmod/UnityIntegration#44]
Hi.  I just realized you are changed the "Total Channel Count" to "Virtual Channel Count". But in-game FMOD Studio Debug tab, this is still named as "total". I dont know if this made on purpose, new users like me would struggle a little by this small thing. Thank you.

https://www.fmod.com/docs/2.00/unity/settings.html#total-channel-count
https://www.fmod.com/docs/2.02/unity/settings.html#virtual-channel-count

![image](https://github.com/fmod/fmod-for-unity/assets/110044633/3b3d3869-631b-45b9-a136-5358fec46951)

**Comment by Connor-FMOD** [comment]
Hi, 

We are using [System::getChannelsPlaying](https://fmod.com/docs/2.02/api/core-api-system.html#system_getchannelsplaying) to get the CHANNELS values. The total value is the realchannels output which is all playing channels both real and virtual so this is accurate. 

Where did the confusion come from? Is there something we could add in the docs to make this clearer?

**Comment by YunusYld** [comment]
> The total value is the realchannels output which is all playing channels both real and virtual so this is accurate.

My bad sorry.

**Comment by Connor-FMOD** [comment]
No worries!
