### ISSUE TITLE
Presence warning in Mobile Build

### ISSUE THREAD

**Issue by YunusYld** [fmod/UnityIntegration#45]
https://github.com/fmod/fmod-for-unity/blob/623658cc07f674e16771b3b37199436f32e12337/Assets/Plugins/FMOD/src/EventHandler.cs#L85C9-L85C9

![image](https://github.com/fmod/fmod-for-unity/assets/110044633/3e08d57e-82bf-4ede-9dd4-28a7efc03449)

**Comment by Connor-FMOD** [comment]
Hi, 

What version of the FMOD integration are you using? Is this happening when building for Both IOS and Android or just one? 

Thanks.

**Comment by Connor-FMOD** [comment]
Hi, 

So the issue is only if an `OnMouse_event` is present in an mobile build. As these should not be included in mobile builds anyway it has been decided not to be changed at this time. 

Thank you for bringing this to our attention.
