### ISSUE TITLE
"Update Event References" Scan throws errors and fails.  Unity 2022.3.18f1 URP

### ISSUE THREAD

**Issue by paulhayes** [fmod/UnityIntegration#46]
Scanning for references fails. Seems to access the UniversalAdditionalCameraData component for some reason. I have no idea why the volume trigger would be accessed by it. Nothing in my code base hooks onto scene changes in the editor or anything like that.

```
UnassignedReferenceException: The variable m_VolumeTrigger of UniversalAdditionalCameraData has not been assigned.
You probably need to assign the m_VolumeTrigger variable of the UniversalAdditionalCameraData script in the inspector.
UnityEngine.Transform+Enumerator.MoveNext () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:690)
FMODUnity.EventReferenceUpdater+<SearchGameObject>d__37.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:337)
FMODUnity.EventReferenceUpdater+<SearchPrefabs>d__34.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:230)
System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () (at <bb4b38eec2634f5887af2d644ab0aceb>:0)
FMODUnity.EventReferenceUpdater.UpdateProcessing () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:1761)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <8e887700cd7e4674989da7b046e8eaa6>:0)

```

**Comment by paulhayes** [comment]
I was able to fix this by adding:
```
if(subObjectField.IsUnityNull() || value.IsUnityNull()){
  continue;
}
```
to line 688 of ```EventReferenceUpdater.cs```

**Comment by KrynnP** [comment]
still error...
fmod 2.02.22
unity 2022.3.20f1

UnassignedReferenceException: The variable m_VolumeTrigger of UniversalAdditionalCameraData has not been assigned.
You probably need to assign the m_VolumeTrigger variable of the UniversalAdditionalCameraData script in the inspector.
UnityEngine.Transform+Enumerator.MoveNext () (at <6f7018b8b8c149e68c4a65a05ac289be>:0)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:690)
FMODUnity.EventReferenceUpdater+<SearchGameObject>d__37.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:337)
FMODUnity.EventReferenceUpdater+<SearchPrefabs>d__34.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:230)
System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () (at <52f66f0a2edb4e51b70e238ffa2df44e>:0)
FMODUnity.EventReferenceUpdater.UpdateProcessing () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:1761)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <5d5ebefe97114215928ac1d9cd096522>:0)



NullReferenceException
UnityEngine.Transform+Enumerator.MoveNext () (at <6f7018b8b8c149e68c4a65a05ac289be>:0)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:690)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:701)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:701)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:692)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:692)
FMODUnity.EventReferenceUpdater+<SearchScriptableObjects>d__35.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:263)
System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () (at <52f66f0a2edb4e51b70e238ffa2df44e>:0)
FMODUnity.EventReferenceUpdater.UpdateProcessing () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:1761)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <5d5ebefe97114215928ac1d9cd096522>:0)



UnassignedReferenceException: The variable m_VolumeTrigger of UniversalAdditionalCameraData has not been assigned.
You probably need to assign the m_VolumeTrigger variable of the UniversalAdditionalCameraData script in the inspector.
UnityEngine.Transform+Enumerator.MoveNext () (at <6f7018b8b8c149e68c4a65a05ac289be>:0)
FMODUnity.EventReferenceUpdater+<GetGenericUpdateTasks>d__45.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:690)
FMODUnity.EventReferenceUpdater+<SearchGameObject>d__37.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:337)
FMODUnity.EventReferenceUpdater+<SearchScenes>d__36.MoveNext () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:307)
System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () (at <52f66f0a2edb4e51b70e238ffa2df44e>:0)
FMODUnity.EventReferenceUpdater.UpdateProcessing () (at Assets/Plugins/FMOD/src/Editor/EventReferenceUpdater.cs:1761)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <5d5ebefe97114215928ac1d9cd096522>:0)

**Comment by KrynnP** [comment]
plz check...

                foreach (FieldInfo subObjectField in subObjectFields)
                {
                    if (subObjectField.IsUnityNull())
                        continue;

                    object value = subObjectField.GetValue(target);
                    if (value.IsUnityNull())
                        continue;

                    if (value != null && !parents.Contains(value))
                    {
                        if (value is System.Collections.IEnumerable)
                        {
                          // search too slow...
                           /*
                            int index = 0;
                            foreach (object item in value as System.Collections.IEnumerable)
                            {
                                foreach (Task t in GetGenericUpdateTasks(item, FieldPath(subObjectPath, subObjectField.Name, index), parents))
                                {
                                    yield return t;
                                }
                                index++;
                            }
                           */
                        }
                        else
                        {
                            foreach (Task t in GetGenericUpdateTasks(value, FieldPath(subObjectPath, subObjectField.Name), parents))
                            {
                                yield return t;
                            }
                        }

**Comment by fmod-cameron** [comment]
We have some fixes for the `EventReferenceUpdater` coming in the next release, 2.02.23.
