### ISSUE TITLE
Unity Build Error 

### ISSUE THREAD

**Issue by sherlock221** [fmod/UnityIntegration#47]
I’m getting the following errors in unity trying to create a build.(Switch buld)
‘xx_VERSION’ does not contain a definition for ‘dll’

FMOD unity 2.02.19
Switch sdk 17.5.3
unity editor 2022.3.16

Assets\Plugins\FMOD\src\fmod_studio.cs(384,35): error CS0117: 'STUDIO_VERSION' does not contain a definition for 'dll'

Assets\Plugins\FMOD\src\fmod_studio.cs(1483,35): error CS0117: 'STUDIO_VERSION' does not contain a definition for 'dll'

Assets\Plugins\FMOD\src\fmod_studio.cs(1774,35): error CS0117: 'STUDIO_VERSION' does not contain a definition for 'dll'

Assets\Plugins\FMOD\src\fmod.cs(975,28): error CS0117: 'VERSION' does not contain a definition for 'dll'

Assets\Plugins\FMOD\src\fmod_studio.cs(1485,35): error CS0117: 'STUDIO_VERSION' does not contain a definition for 'dll'

I don’t know if there’s anyone with the same problem as me who can help me… thank you

**Comment by Connor-FMOD** [comment]
The issue is caused by a Unity Version miss match. Solution shared here: [https://qa.fmod.com/t/unity-build-switch-error/21288/6](https://qa.fmod.com/t/unity-build-switch-error/21288/6).
